### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rollcat** [xykong/macos-sensor-exporter#1]
@xykong there is currently no license specified for your code. I found the code useful, but without an explicit license, I'm technically not even allowed to run it.

I would suggest an MIT license.

**Comment by xykong** [comment]
Hi @rollcat, I'm very happy to know that this project can helps you.  I'll add a license for this.

**Comment by rollcat** [comment]
[Wonderful](https://github.com/xykong/macos-sensor-exporter/commit/1542544ded6a72231f7a153633845b5608ae600b), thank you!
